name: Microservices-Spring-Boot-and-Spring-Cloud
services:
  product:
    image: ch04-product-service:v1.0.0
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512m

  product-composite:
    image: ch04-product-composite-service:v1.0.0
    depends_on:
      review:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '127.0.0.1:8080:8080'
    mem_limit: 512m

  recommendation:
    image: ch04-recommendation-service:v1.0.0
    depends_on:
      product:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512m

  review:
    image: ch04-review-service:v1.0.0
    depends_on:
      recommendation:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512m
