name: chapter04
services:
  product:
    build: microservices/product-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512m

  product-composite:
    build: microservices/product-composite-service
    depends_on:
      review:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '127.0.0.1:8080:8080'
    mem_limit: 512m

  recommendation:
    build: microservices/recommendation-service
    depends_on:
      product:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512m

  review:
    build: microservices/review-service
    depends_on:
      recommendation:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512m
