name: chapter15-kafka
services:
  auth-server:
    build: spring-cloud/authorization-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    healthcheck:
      test: [ "CMD", "wget", "-O -", "-q", "http://localhost:9999/actuator/health" ]
      interval: 5s
      timeout: 2s
      retries: 60
    mem_limit: 512m

  config-server:
    build: spring-cloud/config-server
    volumes:
      - $PWD/config-repo:/config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native
      - ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}
    mem_limit: 512m

  eureka:
    build: spring-cloud/eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    mem_limit: 512m

  gateway:
    build: spring-cloud/gateway
    depends_on:
      auth-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    ports:
      - '8443:8443'
    mem_limit: 512m

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - '9092:9092'
    restart: always
    mem_limit: 1024m

  mongodb:
    image: mongo:8.0.5
    ports:
      - '27017:27017'
    command: mongod
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 5s
      timeout: 2s
      retries: 60
    mem_limit: 512m

  mysql:
    image: mysql:9.2.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    ports:
      - '3306:3306'
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60
    mem_limit: 512m
  product:
    build: microservices/product-service
    depends_on:
      kafka:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    mem_limit: 512m

  product-composite:
    build: microservices/product-composite-service
    depends_on:
      auth-server:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,kafka
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    mem_limit: 512m

  product-p1:
    build: microservices/product-service
    depends_on:
      kafka:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    mem_limit: 512m

  recommendation:
    build: microservices/recommendation-service
    depends_on:
      kafka:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    mem_limit: 512m

  recommendation-p1:
    build: microservices/recommendation-service
    depends_on:
      kafka:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    mem_limit: 512m

  review:
    build: microservices/review-service
    depends_on:
      kafka:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    mem_limit: 512m

  review-p1:
    build: microservices/review-service
    depends_on:
      kafka:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    mem_limit: 512m

  zipkin-server:
    image: openzipkin/zipkin:3.5.0
    environment:
      - STORAGE_TYPE=mem
    ports:
      - '9411:9411'
    restart: always
    mem_limit: 1024m

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - '2181:2181'
    restart: always
    mem_limit: 512m
