name: chapter07-basic
services:

  mongodb:
    image: mongo:8.0.5
    ports:
      - '127.0.0.1:27017:27017'
    command: mongod
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 5s
      timeout: 2s
      retries: 60
    mem_limit: 512m

  mysql:
    image: mysql:9.2.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    ports:
      - '127.0.0.1:3306:3306'
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60
    mem_limit: 512m
  product:
    build: microservices/product-service
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512m

  product-composite:
    build: microservices/product-composite-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '127.0.0.1:8080:8080'
    mem_limit: 512m

  rabbitmq:
    image: rabbitmq:4.0.7-management
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 2s
      retries: 60
    mem_limit: 512m

  recommendation:
    build: microservices/recommendation-service
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512m

  review:
    build: microservices/review-service
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512m
