name: chapter09-kafka
services:
  eureka:
    build: spring-cloud/eureka-server
    ports:
      - '127.0.0.1:8761:8761'
    mem_limit: 512m

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - '127.0.0.1:19092:9092'
    restart: always
    mem_limit: 1024m

  mongodb:
    image: mongo:8.0.5
    ports:
      - '127.0.0.1:27017:27017'
    command: mongod
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 5s
      timeout: 2s
      retries: 60
    mem_limit: 512m

  mysql:
    image: mysql:9.2.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    ports:
      - '127.0.0.1:3306:3306'
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60
    mem_limit: 512m
  product:
    build: microservices/product-service
    depends_on:
      kafka:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
    mem_limit: 512m

  product-composite:
    build: microservices/product-composite-service
    depends_on:
      kafka:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,kafka
    ports:
      - '127.0.0.1:8080:8080'
    mem_limit: 512m

  product-p1:
    build: microservices/product-service
    depends_on:
      kafka:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
    mem_limit: 512m

  recommendation:
    build: microservices/recommendation-service
    depends_on:
      kafka:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
    mem_limit: 512m

  recommendation-p1:
    build: microservices/recommendation-service
    depends_on:
      kafka:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
    mem_limit: 512m

  review:
    build: microservices/review-service
    depends_on:
      kafka:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
    mem_limit: 512m

  review-p1:
    build: microservices/review-service
    depends_on:
      kafka:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
    mem_limit: 512m

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - '127.0.0.1:2181:2181'
    restart: always
    mem_limit: 512m
